name: Setup Python Dependencies
description: Install Python and required dependencies for semantic release

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install cohere
