name: Core Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'core/**'
      - '.github/workflows/core-release.yml'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./core

      - name: Dry Run on develop
        if: github.ref_name == 'develop'
        working-directory: ./core
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Dry-run for develop branch"
          npx semantic-release --extends=.releaserc.json --dry-run

      - name: Full Release on main
        if: github.ref_name == 'main'
        working-directory: ./core
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Running full semantic release on main"
          npx semantic-release --extends=.releaserc.json