name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: js-service/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./js-service

      - name: Semantic Release
        run: npx semantic-release
        working-directory: ./js-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          