name: Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'js-service/**'
      - '.github/workflows/js-release.yml'
      - 'README.md'
      - '.nvmrc'


permissions:
  contents: write  # Required by semantic-release to push tags/releases
  id-token: write  # Required by semantic-release to create GitHub releases


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: js-service/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./js-service

      - name: Show current branch
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: |
          echo "Current branch: ${{ env.CURRENT_BRANCH }}"
      - name: Dry-run on develop (check version bump)
        if: github.ref_name == 'develop'
        id: js_version_check
        run: |
          npx semantic-release --dry-run > dry-run.log || true
          cat dry-run.log
          VERSION=$(grep -oP 'next release version is \K.*' dry-run.log || echo "none")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ./js-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Skip release (develop, no version bump)
        if: github.ref_name == 'develop' && steps.js_version_check.outputs.VERSION == 'none'
        run: echo "Skipping release — no version bump detected."

      - name: Release changelog (develop with version bump)
        if: github.ref_name == 'develop' && steps.js_version_check.outputs.VERSION != 'none'
        run: npx semantic-release --dry-run
        working-directory: ./js-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
      - name: Full release on main
        if: github.ref_name == 'main'
        run: npx semantic-release
        working-directory: ./js-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        

          