name: Python Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'python-service/**'
      - '.github/workflows/python-release.yml'
      - 'README.md'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .[dev]
          pip install python-semantic-release
        working-directory: ./python-service


      - name: Show current branch
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: |
          echo "Current branch: ${{ env.CURRENT_BRANCH }}"


    # Dry-run only if develop branch AND version bump is detected      
      - name: Dry run on develop
        if: github.ref_name == 'develop'
        working-directory: ./python-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Dry run step for develop branch (no operation defined)"
          ln -s ../.git .git  # ensure Git context
          semantic-release version --no-commit
          semantic-release changelog


      - name: Full release on main
        if: github.ref_name == 'main'
        working-directory: ./python-service
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: |
          echo "Running full semantic release on main"
          source venv/bin/activate
          semantic-release publish
        