name: Universal Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
    - 'js-service/**'
    - 'python-service/**'
    - 'java-service/**'
    - 'core/**'
    - 'release-cli.py'
    - '.github/workflows/universal-release.yml'
    - '.github/actions/setup-python-deps/action.yml'

  workflow_dispatch:

jobs:
  detect-changed-folder:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.detect.outputs.languages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug Show Changed Files
        run: |
          git log --oneline -n 2
          echo "Changed files:"
          git diff --name-only HEAD^

      - name: Detect changed language(s)
        id: detect
        run: |
          langs=$(python3 release-cli.py ${{ github.workspace }} | grep -i "languages=" | cut -d= -f2-)
          echo "languages<<EOF" >> $GITHUB_OUTPUT
          echo "$langs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Debug Output
        run: "echo \"Languages: ${{ steps.detect.outputs.languages }}\""

  release-per-language:
    needs: detect-changed-folder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJson(needs.detect-changed-folder.outputs.languages) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semantic Release for ${{ matrix.language }}
        run: |
          echo "Running release for language: ${{ matrix.language }}"
          python3 release-cli.py . --run
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}


  release-js:
    if: needs.detect-changed-folder.outputs.languages == 'javascript' 
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install JS Dev Dependencies
        run: npm install
        working-directory: js-service

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-deps
        
      - name: Run JS Release
        run: npx semantic-release
        working-directory: js-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          
      - name: Upload Release Notes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RELEASE_NOTES.md
          path: "**/RELEASE_NOTES.md"

  release-python:
    if: needs.detect-changed-folder.outputs.languages == 'python'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'     

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js Dev dependencies
        run: npm install
        working-directory: python-service

      - name: Patch invalid version before install
        run: |
          sed -i 's/-develop\./.dev/' python-service/python_servicepkg/__init__.py
  

      - name: Install Python Dev dependencies
        run: |
          pip install -e .[dev]
        working-directory: python-service

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-deps

      - name: Run Python Release
        run: npx semantic-release
        working-directory: python-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Upload Release Notes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RELEASE_NOTES.md
          path: "**/RELEASE_NOTES.md"
       
  release-java:
    if: needs.detect-changed-folder.outputs.languages == 'java'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS Dev Dependencies
        run: npm install
        working-directory: java-service

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-deps
        
      - name: Run Java Release
        run: npx semantic-release
        working-directory: java-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Upload Release Notes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RELEASE_NOTES.md
          path: "**/RELEASE_NOTES.md"

  release-core:
    if: needs.detect-changed-folder.outputs.languages == 'core'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - name: Install Core Dev dependencies
        run: npm install 
        working-directory: core

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-deps
            
      - name: Run Core Release
        run: npx semantic-release
        working-directory: core
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Upload Release Notes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RELEASE_NOTES-${{ needs.detect-changed-folder.outputs.languages }}.md
          path: "**/RELEASE_NOTES.md"