name: Universal Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
    - 'js-services/**'
    - 'python-services/**'
    - 'java-services/**'
    - 'core/**'
    - 'release-cli.py'
    - '.github/workflows/universal-release.yml'

  workflow_dispatch:

jobs:
  detect-changed-folder:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.detect.outputs.language }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Detect changed language
        id: detect
        run: |
          echo "Detecting changed language"
          lang=$(python release-cli.py ${{ github.workspace}} | grep -i "language=" | cut -d= -f2)
          echo "Detected language: $lang"
          echo "language=$lang" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-js:
    if: needs.detect-changed-folder.outputs.language == 'javascript' 
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Run JS Release
        run: npx semantic-release
        working-directory: js-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
  release-python:
    if: needs.detect-changed-folder.outputs.language == 'python'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'     

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python Dev dependencies
        run: |
          pip install -e .[dev]
        working-directory: python-service

      - name: Run Python Release
        run: npx semantic-release
        working-directory: python-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       
  release-java:
    if: needs.detect-changed-folder.outputs.language == 'java'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - name: Run Java Release
        run: npx semantic-release
        working-directory: java-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release-core:
    if: needs.detect-changed-folder.outputs.language == 'core'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - name: Install Core Dev dependencies
        run: npm install 
        working-directory: core
            
      - name: Run Core Release
        run: npx semantic-release
        working-directory: core
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}