name: Universal Semantic Release

on:
  push:
    branches:
      - main
      - develop
    paths:
    - 'js-service/**'
    - 'python-service/**'
    - 'java-service/**'
    - 'core/**'
    - 'release-cli.py'
    - '.github/workflows/universal-release.yml'

  workflow_dispatch:

jobs:
  detect-changed-folder:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.detect.outputs.language }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug Show Changed Files
        run: |
          git log --oneline -n 2
          echo "Changed files:"
          git diff --name-only HEAD^

      - name: Detect changed language
        id: detect
        run: |
          lang=$(python3 release-cli.py ${{ github.workspace }} | grep -i "language=" | cut -d= -f2 | xargs)
          echo "language=$lang"
          echo "language=$lang" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Debug Output
        run: echo "Language was ${{ steps.detect.outputs.language }}"


  release-js:
    if: needs.detect-changed-folder.outputs.language == 'javascript' 
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install JS Dev Dependencies
        run: npm install
        working-directory: js-service
        
      - name: Run JS Release
        run: npx semantic-release
        working-directory: js-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
  release-python:
    if: needs.detect-changed-folder.outputs.language == 'python'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'     

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js Dev dependencies
        run: npm install
        working-directory: python-service

      - name: Patch invalid version before install
        run: |
          sed -i 's/-develop\./.dev/' python-service/python_servicepkg/__init__.py
  

      - name: Install Python Dev dependencies
        run: |
          pip install -e .[dev]
        working-directory: python-service

      - name: Run Python Release
        run: npx semantic-release
        working-directory: python-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       
  release-java:
    if: needs.detect-changed-folder.outputs.language == 'java'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS Dev Dependencies
        run: npm install
        working-directory: java-service
        
      - name: Run Java Release
        run: npx semantic-release
        working-directory: java-service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release-core:
    if: needs.detect-changed-folder.outputs.language == 'core'
    runs-on: ubuntu-latest 
    needs: detect-changed-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - name: Install Core Dev dependencies
        run: npm install 
        working-directory: core
            
      - name: Run Core Release
        run: npx semantic-release
        working-directory: core
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}